### ISSUE TITLE
skinDenoise crash cause by division zero

### ISSUE THREAD

**Issue by mariahyang** [cpuimage/skin_smoothing#1]
core dmp shows:

f0 in skinDenoise (
input=0x7f29cf915540 "\005H\247\005H\247\005H\247\005H\247",
output=0x7f29cd792740 "", width=640, height=304, channels=3, radius=31130,

(gdb) p masked_edge
$2 = -1
(gdb) p edge
$3 = 0
(gdb) p var
$4 = -2
(gdb) p smoothLut[scanInLine[c]]
$5 = 2
(gdb) q

so var + smoothLut[scanInLine[c]] = 0 

const int out = masked_edge - diff * var / (var + smoothLut[scanInLine[c]]);

this will crash cause by division zero

**Comment by PureHing** [comment]
@mariahyang Did you solve it?
@cpuimage Excuse me, how can I modify it?Please tell me.

**Comment by cpuimage** [comment]
@mariahyang @PureHing   

new commits have been fixed.
